<a href="https://colab.research.google.com/github/himanshugaur17/machine-learning-algos/blob/main/svm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import seaborn as sns
import scipy.sparse as sp
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [35]:
class SVMClassifier:
    def __init__(self, lam):
      self.regularizer=lam
      self.theta=None
      self.b=None

    def loss(self, h, y):
      n=y.shape[0]
      squared_theta_sum=np.dot(self.theta,self.theta.T)
      average_squared_theta_sum=(self.regularizer*squared_theta_sum)
      y_dot_h=1-h*y
      return (np.sum(y_dot_h.clip(min=0))+average_squared_theta_sum)/(2*n)

    def fit(self, X, y, n_iters = 100, alpha = 1):
      n,k=X.shape
      loss_list=[]
      self.theta=np.zeros((k,))
      self.b=0
      h=self.decision_function(X)
      loss_list.append(self.loss(h,y))
      for i in range(n_iters):
        h=self.decision_function(X)
        condition=y*h<=1

        y_sum=-1*(y[condition].sum())
        x_multiplied_y=(np.where(condition,1,0).reshape(-1,1))*(y.reshape(-1,1)*X)
        x_multiplied_y_summation=-1*(np.sum(x_multiplied_y,axis=0))+np.multiply(2*self.regularizer,self.theta)

        self.b=self.b-(alpha/(2*n))*(y_sum)
        self.theta=self.theta-(alpha/(2*n))*(x_multiplied_y_summation)

        h=self.decision_function(X)
        loss_list.append(self.loss(h,y))
      return loss_list

    def get_params(self):
      return self.theta,self.b

    def decision_function(self, X):
      h=np.dot(X,self.theta.T)+self.b
      return h

    def predict(self, X):
      h=self.decision_function(X)
      return np.where(h>=0,1,-1)

def binary_svm_classifier(lam = 1e-4):
    return SVMClassifier(lam)

In [37]:
def test_binary_svm_classifier():
    X = np.array([[-2, 4], [4, 1], [1, 6], [2, 4], [6, 2]])
    y = np.array([-1, -1, 1, 1, 1])
    svm = binary_svm_classifier(lam = 1e-4)

    # gradient descent 1000 iters
    losses = svm.fit(X, y, n_iters = 1000)
    theta, b = svm.get_params()
    assert np.allclose(theta, [0.58802283, 1.17683636])
    assert np.allclose(b, -4.8)
    assert np.allclose(losses[-1], 1.7307146603971552e-05)
    assert np.allclose(svm.decision_function(X), [-1.26870024, -1.27107231, 2.84904097, 1.08339109, 1.08180971])
    assert list(svm.predict(X)) == [-1, -1, 1, 1, 1]


test_binary_svm_classifier()

[0.5]
All tests passed!


In [10]:
y.reshape(-1,1)*X

array([[ 2, -4],
       [-4, -1],
       [ 1,  6],
       [ 2,  4],
       [ 6,  2]])

In [14]:
z=(np.where(y>=1,1,0).reshape(-1,1))*(y.reshape(-1,1)*X)

In [15]:
print(z)

[[0 0]
 [0 0]
 [1 6]
 [2 4]
 [6 2]]


In [17]:
-1*(z.sum(axis=0))

array([ -9, -12])